@startuml ex03
left to right direction
actor 学生 as student
actor 教員 as faculty
rectangle {
    usecase "課題の登録" as uc1
    usecase "課題の受領" as uc2
    usecase "リポジトリのクローン" as uc3
    usecase "課題ファイルの修正" as uc4
    usecase "修正をステージに上げる" as uc5
    usecase "修正をコミットする" as uc6
    usecase "リモートリポジトリにpushする" as uc7
    usecase "リポジトリに提出された結果の確認" as uc8
}
uc1 <-- faculty
student --> uc2
student --> uc3
student --> uc4
student --> uc5
student --> uc6
student --> uc7
uc8 <-- faculty
@enduml